 
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
umask 0007
export LANG=C
export LC_ALL=C

# This bash script is for general settings
# for system based settings, a script is used
source $HOME/.my/dotfiles/mod/mod.sh


# source the bioinfotree structure
#source /lustre1/ctgb-usr/.bashrc



##### STANDARD CONFIGURATIONS #####
###################################

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac


# HISTORY #
HISTCONTROL=ignoreboth  # no duplicate lines or lines starting with space in the history
shopt -s histappend   	# append to the history file, don't overwrite it
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s checkwinsize   # update window size after command


if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi


# enable color support
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi




# ALIAS #
#########

alias ls='ls --color="auto"'
alias grep='grep --color="auto"'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias lst='ls --sort=time'
alias size="du -h -d1 | sort -k1hr"



# FUNCTIONS #
#############

function zhead { 
	zcat $1 | head 
}

function ztail { 
	zcat $1 | tail	
}

function zwc { 
	zcat $1 | wc
}

# display the time in a specific format
function prompt_time {
    date +"%H:%M|%d/%m/%y"
}

# display only the beginning and the end of the current wd
function short_wd {
	wd=$(pwd | sed 's/\/home\/gilo/~/')
	if ((${#wd} > 30)); then
		wd="${wd:0:5}...${wd:(-28)}"
	fi
	echo $wd
}

# display the current git branch
function git_branch {
	branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
	if [ $? != 0 ]; 
		then branch="";
    fi

	echo "$branch"
}

# remove the feature of `cd`,
# where if no args are passed it returns to the home dir
# this way, with no args, nothing happens
cd() {
    (( $# > 0)) && builtin cd "$@"
    (( $# == 0 )) && echo "cd: No directory passed as input."
}



# SETTINGS #
############

export PATH=$PATH:$HOME/.my/bin/

# set colorspace to 256 colors 
export TERM=xterm-256color

# set completion
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Created by `pipx` on 2024-12-04 16:09:41
export PATH="$PATH:/Users/sgilotto/.local/bin"

# Added by Windsurf
export PATH="/Users/sgilotto/.codeium/windsurf/bin:$PATH"

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.bash 2>/dev/null || :

# uv
export PATH="/Users/gilotto/.local/bin:$PATH"

# Setting PATH for Python 3.14
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.14/bin:${PATH}"
export PATH

# Added by Antigravity
export PATH="/Users/gilotto/.antigravity/antigravity/bin:$PATH"

# Added by Antigravity
export PATH="/Users/gilotto/.antigravity/antigravity/bin:$PATH"
