
[colors]
# background = #2d353b
background = #009f3ea6
background-alt = #373B41
foreground = #F3F5D9
primary = #b9cef8
pink = #f1739d
blue = #7FBBB3
yellow = #dbbc7f
inactive = #859289
secondary = #8ABEB7
alert = #A54242
disabled = #707880

# This is to set the distance between the modules
[padding]
modules = 5px

# Gradient Set-up
[gradient]
color-1 = #D0ED58
color-2 = #eec5af
color-3 = #aa3fd1


[bar/mybar]
monitor = ${env:MONITOR:}
width = 100%
height = 15 pt
radius = 7
border-color = #00000000
border-left-size = 15
border-right-size = 15
border-top-size = 15
override-redirect = false
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
padding-left = 1
padding-right = 1
module-margin = 0


# side elements
font-0 = CodeNewRomanNerdFont-Bold:weight=bold:size=12;2
# ?
font-1 = CodeNewRomanNerdFont-Bold:weight=bold:size=1;2
# central color gradient
font-2 = CodeNewRomanNerdFont-Bold:weight=bold:size=20;2
#clock
font-3 = Roboto:style=black:size=12;3





# -------------------------------- #
# ORDER 
# -------------------------------- #

modules-left = date
modules-center = xworkspaces
modules-right =  pulseaudio backlight memory battery
# cursor-click = pointer
# cursor-scroll = ns-resize

enable-ipc = true

# tray-position = right

# wm-restack = generic
# wm-restack = bspwm
# wm-restack = i3

# override-redirect = true

# red= "#ff003c"
# blue = "#00d0ff"
# yellow = "fcee09"
# black = "050a0e"

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true

label-active = %name%
label-active-foreground = #000000
label-active-background = #fcee09
label-active-padding = 1

label-occupied = %name%
label-occupied-foreground = #000000
label-occupied-background = #D0ED58
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL:"
format-volume-prefix-foreground = #000000
format-volume-prefix-background = #D0ED58
format-volume = <label-volume>

label-volume = %percentage%%
label-volume-foreground = #000000
label-volume-background = #D0ED58
label-volume-padding-right = 0
label-volume-padding-left = 0

label-muted = "VOL:0%"
label-muted-foreground = #000000
label-muted-background = #D0ED58

# [module/xkeyboard]
# type = internal/xkeyboard
# blacklist-0 = num lock

# label-layout = %layout%
# label-layout-foreground = ${colors.primary}

# label-indicator-padding = 2
# label-indicator-margin = 1
# label-indicator-foreground = ${colors.background}
# label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "||RAM:"
format-prefix-foreground = #000000
format-prefix-background = #D0ED58
label = %percentage_used:2%%
label-foreground = #000000
label-background = #D0ED58


[module/backlight]
type = internal/backlight
card = intel_backlight
use-actual-brightness = true
enable-scroll = true

format = <label>
format-prefix = "||LGTH:"
format-prefix-foreground = #000000
format-prefix-background = #D0ED58
label = %percentage%%
label-background = #D0ED58
label-foreground = #000000
label-padding-right = 0
label-font = 5

[module/cpu]
# type = internal/cpu
# interval = 2
# format-prefix = "CPU "
# format-prefix-foreground = ${colors.primary}
# label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected


[module/wlan]
inherit = network-base
interface-type = wireless
format-connected-prefix = "%{F#dbbc7f}󰖩%{F-}  "
label-connected = On
label-connected-padding-right = ${padding.modules}
label-connected-font = 5


[module/date]
type = internal/date
interval = 1

date-alt = %H:%M
date = "   %H:%M // %a %d %b   "

label = "%date%"
# label-foreground = ${colors.background}
# label-background = #9DA9A0
label-foreground = #000000
label-background = #D0ED58
label-font = 4


[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
time-format = %H:%m
format-charging-prefix ="||BATT:"
format-charging-prefix-background = #D0ED58
format-charging-prefix-foreground = #000000
label-charging = "%percentage%+"
label-charging-background = #D0ED58
label-charging-foreground = #000000
label-charging-font = 5

format-discharging-prefix ="||BATT:"
format-discharging-prefix-background = #D0ED58
format-discharging-prefix-foreground = #000000
label-discharging = "%percentage%-"
label-discharging-background = #D0ED58
label-discharging-foreground = #000000
label-discharging-font = 5

format-full-prefix ="||BATT:"
format-full-prefix-background = #D0ED58
format-full-prefix-foreground = #000000
label-full = "%percentage%"
label-full-background = #D0ED58
label-full-foreground = #000000
label-full-font = 5



[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
